printWidth: 80
tabWidth: 4
useTabs: true
semi: true
singleQuote: false
plugins:
    - "prettier-plugin-svelte"
pluginSearchDirs:
    - "."
overrides":
    - files: "*.svelte"
      options:
          parser: "svelte"
